In [1]:
import pandas as pd

# LOADING DATASET

In [2]:
df = pd.read_csv("sales_practice.csv")

# INSEPECTING DATASET

In [3]:
df.head()

      product region        date  quantity   price
0      Laptop   West  2025-01-01         4  952.59
1      Laptop   East  2025-01-01         5  550.62
2  Smartphone   West  2025-01-01         8  694.11
3      Tablet  South  2025-01-02         2  881.60
4     Monitor  North  2025-01-02         8  490.78

In [4]:
df.tail()

        product region        date  quantity    price
995  Smartphone  North  2025-12-30         4   687.49
996      Tablet  South  2025-12-30         9   946.99
997     Monitor   East  2025-12-30         7   146.95
998  Headphones   West  2025-12-31         8  1114.35
999     Monitor  North  2025-12-31        10  1131.25

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   1000 non-null   object
 1   region    1000 non-null   object
 2   date      1000 non-null   object
 3   quantity  1000 non-null   int64
 4   price     1000 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

# ADDING 'revenue' COLUMN

In [7]:
df['revenue'] = df['price'] * df['quantity']

# FILTERING DATASET

In [27]:
north_df = df[df['region'] == 'North']

In [28]:
north_df.head()

       product region        date  quantity    price   revenue
4      Monitor  North  2025-01-02         8   490.78   3926.24
6       Tablet  North  2025-01-03         8   975.47   7803.76
12     Monitor  North  2025-01-04        10  1010.33  10103.30
14      Tablet  North  2025-01-05         1   237.24    237.24
15  Headphones  North  2025-01-05         1  1036.84   1036.84

# GROUPING DATA BASED ON PRODUCTS

In [16]:
grp = df.groupby(['product'])

## Total Revenue

In [30]:
product_revenue = grp['revenue'].sum().reset_index()

# TOP 5 PRODUCTS

In [32]:
top_5 = product_revenue.sort_values(by='revenue', ascending=False)

In [34]:
top_5

      product    revenue
0  Headphones  765460.42
1      Laptop  757972.29
2     Monitor  673413.33
4      Tablet  652597.85
3  Smartphone  612453.92

# MERGRING DATASETS

In [36]:
final_result = pd.merge(top_5, df, on="product", how="left")

# CREATING A CSV

In [37]:
final_result.to_csv("north_products.csv", index=False)